name: CI/CD test
on: 
  push:
  workflow_dispatch:
jobs:
 Build:
  runs-on: ubuntu-latest
  steps: 
    - uses: actions/checkout@v3
    - name: Compile the code 
      run: echo " Compiling the code"
    - name: Run the testings 
      run: echo "Runing the tests" 
    - name: Build the code
      run: echo "Build the code"
      
 PubImageDocker:
   runs-on: ubuntu-latest
   needs: Build
   steps: 
      - uses: actions/checkout@v3
      - name: Update Docker Image
        run: echo " Update Docker Image " 
      - name: Update Docker registry
        run: echo " Update Docker registry"

      
 PubToAWS:
   runs-on: ubuntu-latest
   needs: PubImageDocker
   steps: 
      - uses: actions/checkout@v3
      - name: Update RDS
        run: echo " Update RDS " 
      - name: Send pictures to s3
        run: echo " Sending the code to ec2"
      - name: Send to Ec2
        run: echo "Build the code"

